"""ShaderForge 确定性领域核心的惰性公共入口."""

from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from shaderforge.analysis import (
        BBoxUv,
        InvalidTargetImageError,
        RadialSegmentStructureEvidenceV1,
        RegionOfInterest,
        TargetHypothesis,
        TargetMeasurements,
        TargetMeasurementsV2,
        TargetMeasurementsV2ArtifactBundle,
        compute_target_hypothesis_hash,
        measure_target,
        measure_target_v2,
        normalize_target_png,
        verify_radial_segment_structure_evidence_v1,
    )
    from shaderforge.compiler import (
        CompilationBundle,
        CompilationProduct,
        CompilerDefectError,
        compile_effect_genome,
        materialize_compilation,
    )
    from shaderforge.contracts import (
        DEFAULT_ACCEPTANCE_POLICY,
        PROBLEM_DOMAINS,
        QUALITY_PRESETS,
        STOP_REASONS,
        WEBGL1_STATIC_NO_TEXTURE_V1,
        AcceptancePolicy,
        BudgetPolicy,
        ProblemDomain,
        QualityPreset,
        RenderContract,
        StopReason,
        budget_for_preset,
    )
    from shaderforge.evaluation import (
        CandidateAttemptRecord,
        CandidateRecord,
        CandidateRecordV2,
        CurrentBestDecision,
        ImageSizeMismatchError,
        MetricWeights,
        RuntimeRequiredLayerMask,
        RuntimeTargetStructureEvidence,
        RuntimeTargetStructureVerification,
        ScoreBreakdownV1,
        evaluate_render,
        max_protected_regression,
        select_current_best,
        verify_runtime_target_structure,
    )
    from shaderforge.generation import (
        MEASUREMENT_AFFINE_SEED_VERSION,
        MeasurementAffineSeed,
        MeasurementSeedProvenance,
        build_measurement_affine_seed,
    )
    from shaderforge.genome import (
        EFFECT_NODE_REGISTRY_V0,
        EffectGenome,
        ParameterSpec,
        TypedEffectGenome,
        compute_genome_hashes,
    )
    from shaderforge.intent import (
        Constraint,
        IntentBuildContext,
        IntentBuildResult,
        IntentIR,
        RequestConstraintSet,
        RequiredLayerAssessment,
        VisualInterpretationV2,
        build_intent_build_context,
        build_intent_variants,
        build_request_constraint_set,
        merge_request_constraint_set,
        parse_visual_interpretation_v2,
        validate_intent_build_result,
        validate_intent_ir,
        validate_request_constraint_set_policy,
    )
    from shaderforge.rendering import (
        CompileResult,
        PlaywrightWebGL1Renderer,
        RendererMetadata,
        RendererUnavailableError,
        RenderResult,
        build_standalone_html,
    )
    from shaderforge.seeding import (
        SeedExpansionResultV2,
        SeedPlanV1,
        build_seed_plans,
        expand_seed_plans,
    )
    from shaderforge.store import (
        ArtifactRef,
        ArtifactRefV2,
        LegacyArtifactRefAdapter,
        LocalArtifactCatalog,
        LocalArtifactStore,
        RunArtifactStore,
    )
    from shaderforge.validation import (
        ValidationResult,
        ValidationViolation,
        validate_shader,
    )

__all__ = [
    "BBoxUv",
    "DEFAULT_ACCEPTANCE_POLICY",
    "PROBLEM_DOMAINS",
    "QUALITY_PRESETS",
    "STOP_REASONS",
    "WEBGL1_STATIC_NO_TEXTURE_V1",
    "AcceptancePolicy",
    "ArtifactRef",
    "ArtifactRefV2",
    "BudgetPolicy",
    "CandidateRecord",
    "CandidateAttemptRecord",
    "CandidateRecordV2",
    "CompilationBundle",
    "CompilationProduct",
    "CompileResult",
    "CompilerDefectError",
    "CurrentBestDecision",
    "EFFECT_NODE_REGISTRY_V0",
    "EffectGenome",
    "ImageSizeMismatchError",
    "IntentBuildContext",
    "IntentBuildResult",
    "IntentIR",
    "InvalidTargetImageError",
    "LegacyArtifactRefAdapter",
    "LocalArtifactCatalog",
    "LocalArtifactStore",
    "MEASUREMENT_AFFINE_SEED_VERSION",
    "MetricWeights",
    "MeasurementAffineSeed",
    "MeasurementSeedProvenance",
    "PlaywrightWebGL1Renderer",
    "ParameterSpec",
    "ProblemDomain",
    "QualityPreset",
    "RegionOfInterest",
    "RadialSegmentStructureEvidenceV1",
    "RequestConstraintSet",
    "RequiredLayerAssessment",
    "RenderContract",
    "RenderResult",
    "RendererMetadata",
    "RendererUnavailableError",
    "RunArtifactStore",
    "RuntimeRequiredLayerMask",
    "RuntimeTargetStructureEvidence",
    "RuntimeTargetStructureVerification",
    "ScoreBreakdownV1",
    "StopReason",
    "TargetHypothesis",
    "TargetMeasurements",
    "TargetMeasurementsV2",
    "TargetMeasurementsV2ArtifactBundle",
    "TypedEffectGenome",
    "ValidationResult",
    "ValidationViolation",
    "VisualInterpretationV2",
    "budget_for_preset",
    "build_standalone_html",
    "build_intent_variants",
    "build_intent_build_context",
    "build_request_constraint_set",
    "build_seed_plans",
    "build_measurement_affine_seed",
    "compute_genome_hashes",
    "compute_target_hypothesis_hash",
    "compile_effect_genome",
    "evaluate_render",
    "expand_seed_plans",
    "max_protected_regression",
    "measure_target",
    "measure_target_v2",
    "merge_request_constraint_set",
    "materialize_compilation",
    "normalize_target_png",
    "verify_radial_segment_structure_evidence_v1",
    "parse_visual_interpretation_v2",
    "select_current_best",
    "verify_runtime_target_structure",
    "validate_shader",
    "validate_intent_ir",
    "validate_intent_build_result",
    "validate_request_constraint_set_policy",
    "Constraint",
    "SeedExpansionResultV2",
    "SeedPlanV1",
]

_EXPORT_MODULES = {
    "DEFAULT_ACCEPTANCE_POLICY": "shaderforge.contracts",
    "PROBLEM_DOMAINS": "shaderforge.contracts",
    "QUALITY_PRESETS": "shaderforge.contracts",
    "STOP_REASONS": "shaderforge.contracts",
    "WEBGL1_STATIC_NO_TEXTURE_V1": "shaderforge.contracts",
    "AcceptancePolicy": "shaderforge.contracts",
    "BudgetPolicy": "shaderforge.contracts",
    "ProblemDomain": "shaderforge.contracts",
    "QualityPreset": "shaderforge.contracts",
    "RenderContract": "shaderforge.contracts",
    "StopReason": "shaderforge.contracts",
    "budget_for_preset": "shaderforge.contracts",
    "CompilationBundle": "shaderforge.compiler",
    "CompilationProduct": "shaderforge.compiler",
    "CompilerDefectError": "shaderforge.compiler",
    "compile_effect_genome": "shaderforge.compiler",
    "materialize_compilation": "shaderforge.compiler",
    "BBoxUv": "shaderforge.analysis",
    "InvalidTargetImageError": "shaderforge.analysis",
    "RegionOfInterest": "shaderforge.analysis",
    "RadialSegmentStructureEvidenceV1": "shaderforge.analysis",
    "TargetMeasurements": "shaderforge.analysis",
    "TargetHypothesis": "shaderforge.analysis",
    "TargetMeasurementsV2": "shaderforge.analysis",
    "TargetMeasurementsV2ArtifactBundle": "shaderforge.analysis",
    "compute_target_hypothesis_hash": "shaderforge.analysis",
    "measure_target": "shaderforge.analysis",
    "measure_target_v2": "shaderforge.analysis",
    "normalize_target_png": "shaderforge.analysis",
    "verify_radial_segment_structure_evidence_v1": "shaderforge.analysis",
    "CandidateRecord": "shaderforge.evaluation",
    "CandidateAttemptRecord": "shaderforge.evaluation",
    "CandidateRecordV2": "shaderforge.evaluation",
    "CurrentBestDecision": "shaderforge.evaluation",
    "ImageSizeMismatchError": "shaderforge.evaluation",
    "MetricWeights": "shaderforge.evaluation",
    "RuntimeRequiredLayerMask": "shaderforge.evaluation",
    "RuntimeTargetStructureEvidence": "shaderforge.evaluation",
    "RuntimeTargetStructureVerification": "shaderforge.evaluation",
    "ScoreBreakdownV1": "shaderforge.evaluation",
    "evaluate_render": "shaderforge.evaluation",
    "max_protected_regression": "shaderforge.evaluation",
    "select_current_best": "shaderforge.evaluation",
    "verify_runtime_target_structure": "shaderforge.evaluation",
    "EFFECT_NODE_REGISTRY_V0": "shaderforge.genome",
    "EffectGenome": "shaderforge.genome",
    "ParameterSpec": "shaderforge.genome",
    "TypedEffectGenome": "shaderforge.genome",
    "compute_genome_hashes": "shaderforge.genome",
    "MEASUREMENT_AFFINE_SEED_VERSION": "shaderforge.generation",
    "MeasurementAffineSeed": "shaderforge.generation",
    "MeasurementSeedProvenance": "shaderforge.generation",
    "build_measurement_affine_seed": "shaderforge.generation",
    "CompileResult": "shaderforge.rendering",
    "PlaywrightWebGL1Renderer": "shaderforge.rendering",
    "RendererMetadata": "shaderforge.rendering",
    "RendererUnavailableError": "shaderforge.rendering",
    "RenderResult": "shaderforge.rendering",
    "build_standalone_html": "shaderforge.rendering",
    "SeedExpansionResultV2": "shaderforge.seeding",
    "SeedPlanV1": "shaderforge.seeding",
    "build_seed_plans": "shaderforge.seeding",
    "expand_seed_plans": "shaderforge.seeding",
    "ArtifactRef": "shaderforge.store",
    "ArtifactRefV2": "shaderforge.store",
    "LegacyArtifactRefAdapter": "shaderforge.store",
    "LocalArtifactCatalog": "shaderforge.store",
    "LocalArtifactStore": "shaderforge.store",
    "RunArtifactStore": "shaderforge.store",
    "Constraint": "shaderforge.intent",
    "IntentBuildContext": "shaderforge.intent",
    "IntentBuildResult": "shaderforge.intent",
    "IntentIR": "shaderforge.intent",
    "RequestConstraintSet": "shaderforge.intent",
    "RequiredLayerAssessment": "shaderforge.intent",
    "VisualInterpretationV2": "shaderforge.intent",
    "build_intent_variants": "shaderforge.intent",
    "build_intent_build_context": "shaderforge.intent",
    "build_request_constraint_set": "shaderforge.intent",
    "merge_request_constraint_set": "shaderforge.intent",
    "parse_visual_interpretation_v2": "shaderforge.intent",
    "validate_intent_ir": "shaderforge.intent",
    "validate_intent_build_result": "shaderforge.intent",
    "validate_request_constraint_set_policy": "shaderforge.intent",
    "ValidationResult": "shaderforge.validation",
    "ValidationViolation": "shaderforge.validation",
    "validate_shader": "shaderforge.validation",
}


def __getattr__(name: str) -> Any:
    """按所属 typed 子包惰性解析兼容导出."""
    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    """返回包含惰性公共名的模块属性列表."""
    return sorted(set(globals()) | set(__all__))
