"""ShaderForge 对其他应用层开放的稳定入口."""

from shaderforge.analysis import (
    InvalidTargetImageError,
    RegionOfInterest,
    TargetMeasurements,
    measure_target,
    normalize_target_png,
)
from shaderforge.contracts.png_to_shader_v1 import (
    DEFAULT_ACCEPTANCE_POLICY,
    PROBLEM_DOMAINS,
    QUALITY_PRESETS,
    STOP_REASONS,
    WEBGL1_STATIC_NO_TEXTURE_V1,
    AcceptancePolicy,
    BudgetPolicy,
    ProblemDomain,
    QualityPreset,
    RenderContract,
    StopReason,
    budget_for_preset,
)
from shaderforge.evaluation import (
    CandidateRecord,
    CurrentBestDecision,
    ImageSizeMismatchError,
    MetricWeights,
    ScoreBreakdownV1,
    evaluate_render,
    max_protected_regression,
    select_current_best,
)
from shaderforge.generation import (
    MEASUREMENT_AFFINE_SEED_VERSION,
    MeasurementAffineSeed,
    MeasurementSeedProvenance,
    build_measurement_affine_seed,
)
from shaderforge.perception import MinPerception, perceive_min_target
from shaderforge.rendering import (
    CompileResult,
    PlaywrightWebGL1Renderer,
    RendererMetadata,
    RendererUnavailableError,
    RenderResult,
    build_standalone_html,
)
from shaderforge.scene import (
    CIRCLE_AXES_TOLERANCE,
    MIN_SCENE_VERSION,
    AddFeaturePatch,
    Canvas,
    ColorField,
    Feature,
    LinearColorField,
    MinScene,
    Primitive,
    RadialColorField,
    RemoveFeaturePatch,
    ReplaceColorFieldPatch,
    ReplaceFeaturePatch,
    SceneObject,
    SolidColorField,
    apply_scene_patch,
)
from shaderforge.store import ArtifactRef, LocalArtifactStore, RunArtifactStore
from shaderforge.validation import (
    ValidationResult,
    ValidationViolation,
    validate_shader,
)

__all__ = [
    "DEFAULT_ACCEPTANCE_POLICY",
    "PROBLEM_DOMAINS",
    "QUALITY_PRESETS",
    "STOP_REASONS",
    "WEBGL1_STATIC_NO_TEXTURE_V1",
    "AcceptancePolicy",
    "ArtifactRef",
    "BudgetPolicy",
    "CandidateRecord",
    "CompileResult",
    "CurrentBestDecision",
    "ImageSizeMismatchError",
    "InvalidTargetImageError",
    "LocalArtifactStore",
    "MEASUREMENT_AFFINE_SEED_VERSION",
    "MinPerception",
    "MinScene",
    "MeasurementAffineSeed",
    "MeasurementSeedProvenance",
    "AddFeaturePatch",
    "CIRCLE_AXES_TOLERANCE",
    "Canvas",
    "ColorField",
    "Feature",
    "LinearColorField",
    "MIN_SCENE_VERSION",
    "MetricWeights",
    "PlaywrightWebGL1Renderer",
    "ProblemDomain",
    "Primitive",
    "QualityPreset",
    "RegionOfInterest",
    "RenderContract",
    "RenderResult",
    "RendererMetadata",
    "RendererUnavailableError",
    "RunArtifactStore",
    "RemoveFeaturePatch",
    "ReplaceColorFieldPatch",
    "ReplaceFeaturePatch",
    "RadialColorField",
    "SceneObject",
    "ScoreBreakdownV1",
    "StopReason",
    "SolidColorField",
    "TargetMeasurements",
    "ValidationResult",
    "ValidationViolation",
    "budget_for_preset",
    "build_standalone_html",
    "apply_scene_patch",
    "build_measurement_affine_seed",
    "evaluate_render",
    "max_protected_regression",
    "measure_target",
    "perceive_min_target",
    "normalize_target_png",
    "select_current_best",
    "validate_shader",
]
