"""V2.2 Effect Genome Deterministic Compiler。."""

from shaderforge.compiler.compiler import (
    compile_diagnostic_passes,
    compile_effect_genome,
    materialize_compilation,
    materialize_diagnostic_compilation,
)
from shaderforge.compiler.models import (
    DETERMINISTIC_COMPILER_VERSION,
    DIAGNOSTIC_OWNERSHIP_POLICY_VERSION,
    DIAGNOSTIC_VISIBLE_DELTA_BYTE_THRESHOLD,
    CompilationBundle,
    CompilationProduct,
    CompilerAst,
    CompilerAstBinding,
    CompilerAstInput,
    CompilerAstNode,
    CompilerDefectError,
    CompilerParameterEntry,
    CompilerParameterTable,
    DiagnosticCompilationBundleV2,
    DiagnosticCompilationBundleV3,
    DiagnosticCompilationProductV2,
    DiagnosticCompilationProductV3,
    DiagnosticPassArtifactV2,
    DiagnosticPassArtifactV3,
    DiagnosticPassSourceV2,
    DiagnosticPassSourceV3,
    NodeLineEntry,
    NodeLineSourceMap,
)

__all__ = [
    "DETERMINISTIC_COMPILER_VERSION",
    "DIAGNOSTIC_OWNERSHIP_POLICY_VERSION",
    "DIAGNOSTIC_VISIBLE_DELTA_BYTE_THRESHOLD",
    "CompilationBundle",
    "CompilationProduct",
    "DiagnosticCompilationBundleV2",
    "DiagnosticCompilationBundleV3",
    "DiagnosticCompilationProductV2",
    "DiagnosticCompilationProductV3",
    "DiagnosticPassArtifactV2",
    "DiagnosticPassArtifactV3",
    "DiagnosticPassSourceV2",
    "DiagnosticPassSourceV3",
    "CompilerAst",
    "CompilerAstBinding",
    "CompilerAstInput",
    "CompilerAstNode",
    "CompilerDefectError",
    "CompilerParameterEntry",
    "CompilerParameterTable",
    "NodeLineEntry",
    "NodeLineSourceMap",
    "compile_diagnostic_passes",
    "compile_effect_genome",
    "materialize_compilation",
    "materialize_diagnostic_compilation",
]
